question_data = [
    {"text": "The first mechanical computer was called the Analytical Engine.", "answer": "True"},
    {"text": "The Python programming language was named after the snake.", "answer": "False"},
    {"text": "HTML stands for HyperText Markup Language.", "answer": "True"},
    {"text": "The first version of Windows was released in 1985.", "answer": "True"},
    {"text": "Bluetooth technology is named after a medieval king.", "answer": "True"},
    {"text": "Java and JavaScript are the same programming language.", "answer": "False"},
    {"text": "The iPhone was first released in 2007.", "answer": "True"},
    {"text": "The term 'spam' for unwanted emails comes from a Monty Python sketch.", "answer": "True"},
    {"text": "Linus Torvalds created the Linux operating system.", "answer": "True"},
    {"text": "CSS stands for Cascading Style Sheets.", "answer": "True"},
    {"text": "The first email was sent in 1971.", "answer": "True"},
    {"text": "RAM stands for Read Access Memory.", "answer": "False"},
    {"text": "Alan Turing is often considered the father of computer science.", "answer": "True"},
    {"text": "SQL stands for Structured Query Language.", "answer": "True"},
    {"text": "The first computer virus was created in the 1980s.", "answer": "True"},
    {"text": "Java was originally developed by Microsoft.", "answer": "False"},
    {"text": "The World Wide Web was invented by Tim Berners-Lee.", "answer": "True"},
    {"text": "An IP address is a unique string of numbers separated by periods.", "answer": "True"},
    {"text": "The first hard drive was created by IBM in 1956.", "answer": "True"},
    {"text": "Apple's Macintosh was the first computer with a graphical user interface.", "answer": "False"},
    {"text": "PHP originally stood for Personal Home Page.", "answer": "True"},
    {"text": "Unicode is a standard for encoding text in different languages.", "answer": "True"},
    {"text": "A terabyte is larger than a petabyte.", "answer": "False"},
    {"text": "The Google Chrome browser was released in 2008.", "answer": "True"},
    {"text": "IPv6 addresses are 64-bit long.", "answer": "False"}
]
